name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Run lint
        run: ./gradlew lint

      - name: Run ktlint
        run: ./gradlew ktlintCheck